version: '2'
services:
  mailserver:
    image: hardware/mailserver
    container_name: mailserver
    domainname: domain.tld              # Mail server FQDN & reverse = mail.domain.tld.
    hostname: mail
    restart: always
    links:
      - mariadb
    # extra_hosts:                        - Required for external database (on other server or for local database on host)
    #  - "mariadb:xx.xx.xx.xx"            - Replace with IP address of MariaDB server
    ports:
      - "25:25"     # SMTP                - Required
    # - "110:110"   # POP3       STARTTLS - Optional - For webmails/desktop clients
      - "143:143"   # IMAP       STARTTLS - Optional - For webmails/desktop clients
    # - "465:465"   # SMTPS      SSL/TLS  - Optional - Enabled for compatibility reason, otherwise disabled
      - "587:587"   # Submission STARTTLS - Optional - For webmails/desktop clients
      - "993:993"   # IMAPS      SSL/TLS  - Optional - For webmails/desktop clients
    # - "995:995"   # POP3S      SSL/TLS  - Optional - For webmails/desktop clients
      - "4190:4190" # SIEVE      STARTTLS - Optional - Recommended for mail filtering
    environment:
      - DBPASS=xxxxxxx
    # - ENABLE_POP3=true          # Enable POP3 protocol
    # - GREYLISTING=gross         # Enable gross greylisting policy server
    # - DISABLE_CLAMAV=true       # Disable virus scanning
    # - DISABLE_SPAMASSASSIN=true # Disable SPAM checking
    # - DISABLE_SIEVE=true        # Disable ManageSieve protocol
    volumes:
      - /var/docker/mail:/var/mail
      - /var/docker/mail/opendkim:/etc/opendkim/keys
      - /var/docker/mail/schleuder:/etc/schleuder
    # - /mnt/docker/nginx/certs:/etc/letsencrypt
    depends_on:
      - mariadb
    networks:
      - proxy-tier


  # Administration interface
  # https://github.com/hardware/postfixadmin
  # http://postfixadmin.sourceforge.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Postfixadmin-initial-configuration
  postfixadmin:
    image: hardware/postfixadmin
    container_name: postfixadmin
    domainname: domain.tld
    hostname: mail
    # restart: always
    environment:
      - DBPASS=xxxxxxx
      - VIRTUAL_HOST=mail.domain.tld
    depends_on:
      - mailserver
      - mariadb
    networks:
      - proxy-tier
  # Webmail (Optional)
  # https://github.com/hardware/rainloop
  # https://www.rainloop.net/
  # Configuration : https://github.com/hardware/mailserver/wiki/Rainloop-initial-configuration
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    restart: always
    volumes:
      - /mnt/docker/rainloop:/rainloop/data
    environment:
      - VIRTUAL_HOST=mail.domain.tld
    depends_on:
      - mailserver
      - mariadb
    networks:
      - proxy-tier
networks:
  proxy-tier:
    external:
      name: nginx-proxy
